### ISSUE TITLE
keyboard widget error with current master branch of tiddlywiki

### ISSUE THREAD

**Issue by felixhayashi** [danielo515/TW5-contextPlugin#10]
Hi @danielo515 

Your keyboard snippets plugin doesn't have a repo so I created an issue here.

Using the current master branch of TiddlyWiki5 and your keyboard snippets plugin will cause an error when editing a tiddler!

![selection_392](https://cloud.githubusercontent.com/assets/4307137/8574044/eb7d8a0c-2594-11e5-9c7e-07cc1eb67759.png)

This error doesn't occur in 5.1.9 but as said in the current tw master branch (5.1.10-prerelease)

-Felix

**Comment by felixhayashi** [comment]
Maybe you have an idea what could cause this @Jermolene?

**Comment by Jermolene** [comment]
I'd be suspicious of the recent optimisation that I've been committing. Again, it would be helpful to do a `git bisect` if you can.

**Comment by danielo515** [comment]
Hello @felixhayashi ,

There is a repo, but Sadly it has the first name I gave it to the plugin: https://github.com/danielo515/TW5-extendTextWidget

I wanted to update it for a long time, and give it a proper plugin structure. But I never found time.

**Comment by felixhayashi** [comment]
@danielo515 After pulling the latest changes from the tw Github repo, everything seems to work again now :) *relief*

> There is a repo, but Sadly it has the first name I gave it to the plugin: https://github.com/danielo515/TW5-extendTextWidget
> I wanted to update it for a long time, and give it a proper plugin structure. But I never found time.

Would be great if you could do so! I guess this is my mostly used plugin :)

-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

Thank you for the ticket report and the ticket close :smile: 
I have been taking notes about new ideas for this plugin, since I use it a lot. It is definitively on my list.

**Comment by felixhayashi** [comment]
> It is definitively on my list.

That is great news! :)
