### ISSUE TITLE
Plugins at github

### ISSUE THREAD

**Issue by felixhayashi** [danielo515/TW5-contextPlugin#2]
Hi @danielo515,

I want to automatically pull the latest versions of your contextPlugin and the Keyboard plugin from github when I build my wikis. its much easier than always opening your demo wiki and dragndrop your plugins.

It would be great if you could create a github "dist" folder for both of these plugins that contain the plugins in a standard "ready to use" form (with plugin.info etc. like tiddlywiki/plugins/*). Then I could simply make a pull from this dist path into my plugins folder and compile everything.

Would this be possible?

Regards
Felix

**Comment by danielo515** [comment]
Hello @felixhayashi , sorry for the late response.

I think some of my plugins have that structure, or at least similar. For example:

https://github.com/danielo515/TW5-TagSearch/tree/master/plugins
 or

https://github.com/danielo515/TiddlyDrive

But I'm affraid that even those does not have the structure that you need. Searching for an example in my repositories I just realized that my github account is a big mess. Most of the plugins have an ugly structure, and some of them does not have a structure at all.The plugins you are asking for were developed on the browser, so I have to find some time to update them when I get time.

Regarding your offer, I am be very interested. Are you using a system like grunt? I read about it, but I never found a scenario where it could be useful. I have MACOS, and windows, and I can use a linux computer if needed.

**Comment by danielo515** [comment]
Hello Felix, 

I think I found a valid example:

https://github.com/danielo515/tiddlywiki-tiddlerVersionsPlugin

Does this fits your structure requirements?

**Comment by felixhayashi** [comment]
Hi @danielo515,

I already thought you were dead :)

> Does this fits your structure requirements?

Well sort of. The point of having a separate `dist/` folder is that `dist/` only includes the stuff used to run the plugin (in case of tiddlywiki a tiddlywiki.info and the plugin stuff). The `src` folder on the other hand may contain everything that relates to your project. For example photoshop images are in `src` and the resulting png are in `dist`. The uncompressed javascript or css is in `src` the compressed js and css is in `dist`.

In summary: such a standard structure makes life easier for users of your plugin and yourself.

> Regarding your offer, I am be very interested. Are you using a system like grunt?

I am using *gulp* which does the same thing like grunt but in a different way. For example see https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/gulpfile.js.

For the vis plugin I use a linux shell script:

https://github.com/felixhayashi/TW5-Vis.js/blob/master/build.sh

> I read about it, but I never found a scenario where it could be useful. I have MACOS, and windows, and I can use a linux computer if needed.

grunt and gulp can be used on any OS. Using a task runner makes sense nowadays. For example css is not written in css anymore but in *sass* (see https://github.com/felixhayashi/TW5-TiddlyMap/blob/master/src/plugins/felixhayashi/tiddlymap/files/layout.scss) or in *less*. Javascript is not written in javascript but using node or coffescript or typescript. So you have to compile everything before you can use it. Compiling needs many steps and you don't want to always execute a command for each step so you use a taskrunner.

Or imagine you have `png` images and need them to be `tid` files. You cannot always drag and drop the images in tiddlywiki and export them to get a `.tid` image but you can use a task runner or build script to convert them to base64 and add all the header information like `title: ...` in the head.

-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

I have to investigate about the task runners and the new ways of programming web applications. I don't have a good programming workflow, I never took a programming lesson. If you have any manual about how to use that kind of software or about some good guidelines I will be very pleased to read it.

Regarding your request, let me know if the current folder structure works for your purposes.

Regards.

**Comment by felixhayashi** [comment]
Hola hombre,

> I have to investigate about the task runners and the new ways of programming web applications. I don't have a good programming workflow, I never took a programming lesson. 

:+1:  great. Workflow is something nobody will teach you at any programming lesson, university, or school. Also usually good programmers are self-taught. Of course you can visit a programming course, but really, you only grow in knowledge if you read programming books (online), work on projects or have a programming related job where your team-mates are experienced programmers.

>  If you have any manual about how to use that kind of software or about some good guidelines I will be very pleased to read it.

I would suggest to do the following. Try to learn by improving the workflow of the context plugin.

If I developed your plugin, I would have the following workflow:

1. I would work with a js editor (e.g. netbeans) on the javascript which lies in `some/path/on/your/pc/src/context-widget.js`
1. Everytime I want to "pack" or "compile" the program, I would
  1. first minify the code (so it doesn't waste space in the wiki). For minifying, the standard program is called "uglifyjs" and is installed via npm. Here you need to make sure uglify doesn't remove your code-header-comment because tiddlywiki needs it.
  1. Then copy the minified script from `some/path/on/your/pc/src/contextplugin/context-widget.min.js` to `dist/context-widget.js`.
1. Now copy all files named `*.tid` into  `some/path/on/your/pc/dist/contextplugin/tiddlers/context-widget.js`.

You will soon realize that it is better to have a little taskrunner that runs all these tasks automatically. So try doing it with e.g. "grunt".  I prefer gulp. If you use gulp, these would be the instructions you need:


    /********************************************************************
     * Imports
     *******************************************************************/

    var gulp = require("gulp");
    var gutil = require("gulp-util");
    var uglify = require("gulp-uglify");
    var del = require("del"); // rm -rf
    //~ var jsdoc = require("gulp-jsdoc"); // not maintained!

    /********************************************************************
     * Tasks
     *******************************************************************/

    gulp.task("clean", function (cb) { 

      var options = { force: true };
      del([ "../dist/" ], options, cb);
      
    });

    gulp.task("compile", ["clean"], function () {

      // copy everything that doesn't need further processing
      gulp.src(["plugins/**", "!plugins/**/*.js"])
        .pipe(gulp.dest("../dist/"));
        
      // uglify js
      gulp.src("plugins/**/*.js")
        .pipe(uglify({ compress: false, preserveComments: "some" }))
        .pipe(gulp.dest("../dist/"));
        
    });


    gulp.task("default", ["compile"]);

To test your plugin without needing drag'n'drop. Look at this great guide by astrid: https://groups.google.com/d/msg/tiddlywiki/7X5nZR5-w8M/qhnNgrjan58J. The tiddlywiki you download from git will have a folder named `tiddlywiki/plugins/` which per default contains stuff like `.../plugins/tiddlywiki/markdown`. You need to make a symbolik link to your plugin `tiddlywiki/plugins/danielo/contextplugin/` which links to the `some/path/on/your/pc/dist/contextplugin/`.

Now everytime you execute the `gulp` command it will move your files and code to `some/path/on/your/pc/dist/contextplugin/`.

Here is how I include your plugin now:

The tiddlywiki.info

    {
      "plugins": [
        "tiddlywiki/github-fork-ribbon",
        "tiddlywiki/markdown",
        "tiddlywiki/highlight",
        "felixhayashi/topstoryview",
        "felixhayashi/vis",
        "felixhayashi/tiddlymap",
        "danielo/contextPlugin"
      ],
    ...

The folder structure of my tiddlywiki

![selection_449](https://cloud.githubusercontent.com/assets/4307137/5799871/b0158610-9fd7-11e4-9e3c-bcd6861109af.png)

Then you need to run the node command like astrid described.

Don't worry, it looks difficult but after some experiments you will see it is not that hard. It also took me a few days to understood how task runners work.

> Regarding your request, let me know if the current folder structure works for your purposes.

Almost, could you move all *.tid files into a folder named tiddler? - while it is not needed, this is a convention for tw plugins. Also the plugin folder is usually written lowercase ("contextPlugin" -> "contextplugin" (see http://tiddlywiki.com/#Naming%20of%20System%20Tiddlers).

Regards
Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

>  you need to make sure uglify doesn't remove your code-header-comment because tiddlywiki needs it.

Is it on the documentation of uglify how to achieve this?

>Now copy all files named *.tid into some/path/on/your/pc/dist/contextplugin/tiddlers/context-widget.js.

I think you included the context-widget.js filename at the end of the path by accident. Right?


>  Is it on the documentation of uglify how to achieve this?

ook, I think is stated here:
```
.pipe(uglify({ compress: false, preserveComments: "some" }))
```

This particular part:

gulp.task("compile", ["clean"], function () {

What is "compile"? the name of the task? I think it first executes the clean task defined above, and then it names the following anonymous function to "compile".

What I think is that you define 3 task, clean,compile and default, and each task depends on the previous one. Then, I don't know how you execute the default task. Right?

> could you move all *.tid files into a folder named tiddler? - while it is not needed, this is a convention for tw plugins.

I did not see this in much plugins. Where is that convention? I used to "clasify" tiddlers based on its role "language" for captions, "ui" for ui tiddlers, and so on. If I put all tid files under the same directory I think it could be a mess.

Regards.

**Comment by felixhayashi** [comment]
By the way, I am sure you know much of the stuff I wrote above, but I just wanted to be complete in my description that is why I explained everything in more detail.

**Comment by felixhayashi** [comment]
> Is it on the documentation of uglify how to achieve this?

Yes, see example gulp file code above. Then in your `*.js` you need to add `@preserve` (see TiddlyMap src files for an example).

> I think you included the context-widget.js filename at the end of the path by accident. Right?

Uups, yes.

> What is "compile"? the name of the task? I think it first executes the clean task defined above, and then it names the following anonymous function to "compile".

Yes, it is the name of the task. the clean is part of an array of tasks that should get executed before compile starts. so it would remove all previous files in dist/ and then run compile.

> I did not see this in much plugins. Where is that convention?

Ehm, I think you are right :)

-Felix
