### ISSUE TITLE
Move your Plugin to a prominent position!

### ISSUE THREAD

**Issue by felixhayashi** [danielo515/TW5-contextPlugin#3]
Hi @danielo515,

your context search is really great, so it should be moved away from advanced search to a better place! Please go to the TiddlyMap demo (http://bit.ly/tiddlymap) site and search for "graph" then click on the context tab. It will appear as "search visualizer" (possible since 5.1.5 - see https://groups.google.com/forum/#!searchin/tiddlywikidev/search$20visualizer/tiddlywikidev/UafAzk5Bt7k/q0afSTIR5AAJ).

What do you think? I include the changed code as pull request.

I should also file a pull request at Jermolene/TiddlyWiki5 that users can choose their favorite search visualizer per drop down in "configuration", so it is displayed as default. For TiddlyMap, a graph is show to visualize results per default.

-Felix

**edit**

When I said "moved away from advanced search" i really meant " it should also be displayed at another (better) place! It can still exist in advanced search of course ;)

**Comment by felixhayashi** [comment]
![selection_452](https://cloud.githubusercontent.com/assets/4307137/5802689/885599ec-9ff7-11e4-8f8d-de44cf64c4a6.png)

**Comment by danielo515** [comment]
Hello @felixhayashi 

Thank you very much! you made me so happy. My first pull request. You can ask my girlfriend what I have asked for Christmas:
> "A pull request on any of my repositories"

I can't see any pull request on my repository. Could you check if you made the pull request to it?

Regards

**Comment by felixhayashi** [comment]
Hola @danielo515,

> Thank you very much! you made me so happy. My first pull request. You can ask my girlfriend what I have asked for Christmas:
>>  "A pull request on any of my repositories"

Danielo, if you feel this way, you certainly are a true programmer :) I know it feels great if a project gets the deserved attention :)

> I can't see any pull request on my repository. Could you check if you made the pull request to it?

![selection_453](https://cloud.githubusercontent.com/assets/4307137/5804921/75b28346-a00a-11e4-9e19-68efebe534e2.png)

Felix ;)

**Comment by danielo515** [comment]
> Danielo, if you feel this way, you certainly are a true programmer :) 
Thank you for the kind words

> I know it feels great if a project gets the deserved attention :)
Indeed

Regarding the pull request, I think I did not explained myself well. I clicked on the referenced pull request, but it looks like a pull request to your own fork. If I go there there is no "merge" button. In fact, if you go to my repository and click on pull request there is nothing, but if you go to your fork and click on pull request there is once. And, as github says, only administrators can merge pull request on your repository.

**Comment by felixhayashi** [comment]
Hi @danielo515,

Yes, I agree, pull requests should be made to the correct repository :)

Sorry for me being stupid.

-Felix

**Comment by felixhayashi** [comment]
:blush: yay it was accepted

**Comment by danielo515** [comment]
Of course! It was a good one
