### ISSUE TITLE
Allow to show context below 4 characters

### ISSUE THREAD

**Issue by felixhayashi** [danielo515/TW5-contextPlugin#6]
Hi @danielo515,

is it possible to configure the plugin to start showing highlighted results, even though the user only entered 3 characters?

-Felix

**Comment by danielo515** [comment]
I was going to say, yes it is, but after checking the documentation it is not specified. Seems that I thoug about implementing it but I never did.

**Comment by felixhayashi** [comment]
:) So maybe you could add an option?

**Comment by danielo515** [comment]
Yes, definitively

**Comment by felixhayashi** [comment]
Nice, thanks

**Comment by felixhayashi** [comment]
Hi @danielo515, please accept the request, thanks!

**Comment by danielo515** [comment]
Hello @felixhayashi 

I think I did it some time ago :)
Thank you and regards

**Comment by felixhayashi** [comment]
Hola @danielo515,

> I think I did it some time ago :) Thank you and regards

yes, I saw it, thanks :) Please also add a BSD/MIT license to your repo, so I can continue to use it on the demo site of tiddlymap and in my other projects. All of them are compatible with Tiddlywiki. 

Thanks

-Felix
