### ISSUE TITLE
License

### ISSUE THREAD

**Issue by felixhayashi** [danielo515/TW5-contextPlugin#7]
Hi @danielo515,

could you please add a `LICENSE` file to this repository with bsd clause 2 or clause 3 license (this is what tw uses)? Otherwise I cannot use your plugin on my site and I really want to use it :)

Thanks
-Felix

**Comment by danielo515** [comment]
Hello @felixhayashi 

I'm not very experienced with Licensed. Will CC license allow you to use my plugin also? It's mandatory to use BSD because it's a TW plugin?
What clauses 2 an 3 means?

**Comment by felixhayashi** [comment]
Hola @danielo515,

> Will CC license allow you to use my plugin also? It's mandatory to use BSD because it's a TW plugin?

The problem is that your plugin can never make it into the core (and I think it should at some point!) because the cc license is much more restrictive and does not give the user as much freedom as a bsd license and tiddlywiki uses bsd (3-clause). If you want don't want to give a user any kind of headache, use a BSD or Apache License. This will make your plugin more attractive since nobody needs to be afraid of violating the license because it is kept very minimal. Also the BSD License allows proprietary/commercial use which is important.

I use "bsd 2-clause" for tiddlymap so the user does not need to contact me to use tiddlymap to promote his/her product in contrast to "bsd 3-clause".

Hope that helps :)

**Comment by felixhayashi** [comment]
Also do not use CC license for *software* in any case:

> Avoid using the “Creative Commons” licenses for software. The Creative Commons FAQ says, “Creative Commons licenses are not intended to apply to software. They should not be used for software... [they don’t distinguish, as needed,] between object and source code... We strongly encourage you to use one of the very good software licenses available today [instead].” Jay Tuley’s “5 reasons to not choose a CC license for code” explains more. The debian-legal Summary of Creative Commons 2.0 Licenses recommends that authors who wish to create works compatible with Debian’s “Debian Free Software Guidelines” should not use any of the licenses in the Creative Commons license suite; licenses with the “NonCommercial” or “NoDerivs” license elements are fundamentally incompatible with FLOSS, authors who use or are planning to use the Attribution 2.0 license should consider a similar Free Software license such as a BSD- or MIT-style license..., and Authors who use or are planning to use the Attribution-ShareAlike 2.0 license should consider a similar Free Software license such as the GNU General Public License [GPL]. The Creative Commons has “wrapped” the GPL and LGPL if you want to use the Creative Commons search engine. 
> http://www.dwheeler.com/essays/gpl-compatible.html

**Comment by felixhayashi** [comment]
@danielo515 Any updates on this? And could you please have a look at my pull request?

Thanks

**Comment by danielo515** [comment]
Hello @felixhayashi 

I want to allow people to use my plugin, but I want to be noticed if someone wants to use it for commercial use. No to restrict but to add it to my portfolio. I'm not very skilled with licences, so I will accept your advice. What should I do exactly? From where I can get the BSD clause 3? Is just a matter of coping it on a .md file and call it licence?

Regarding your pull request, I think it is closed and accepted.

Regards

**Comment by felixhayashi** [comment]
Hi @danielo515,

> I want to allow people to use my plugin, but I want to be noticed if someone wants to use it for commercial use. No to restrict but to add it to my portfolio. I'm not very skilled with licences, so I will accept your advice. 

I am also not a lawyer, but here is my opinion on this issue:

1. A license that says "contact the copyright holder before commercial use" is really restrictive and will prevent the plugin from being used since the license taker needs to create a legal document in which he describes his project and send it to the copyright holder. The holder may say "ok, use my software" but the license taker always has to fear that the copyright holder says "wait a minute, you are using my software in a way I did not allow you to use it."
2. I am not aware of an open source license that forces the license taker to contact the author. Neither MIT/BSD/Apache/GPL/CC... That is the point of a license, to not ask for permission but to instantly know how to use it.
3. When you use e.g. BSD 3-Clause, you as the copyright holder will get credit for your work because everybody using the code has to keep your name as comment in the code or in the credits list or license info file. You can then use google to search for your name to keep track of people using the plugin ;)

So my advice, use BSD as it is the same license as tw and very minimal so everybody (commercial/not commercial can use your product). You may at any time change the license (since you are the copyright holder).

> What should I do exactly? From where I can get the BSD clause 3? Is just a matter of coping it on a .md file and call it licence?

Its very simple. Copy paste the text from http://opensource.org/licenses/BSD-3-Clause and replace the placeholders then just create a LICENSE file in your repo. That's it ;)

> Regarding your pull request, I think it is closed and accepted.

:+1: 

-Felix
